spring:
  profiles:
    active: dev
  application:
    name: ScientificResearchAuditSystem
  freemarker:
    suffix: .ftl
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
springfox:
  documentation:
    swagger-ui:
      enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8181
qiniu:
  accessKey: pMZtit7DLynmLmY1Wc3X6PPdgCSvWRrwnfUPGTce
  accessSecretKey: QHSlrMKglANCOSJ-cbloV3ojpvu01nfIYw3JmB1f
  bucket: ivan-paper
  imageUrl: http://static.ivanlife.cn
