spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/paper?useSSL=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
  devtools:
    restart:
      enabled: true
  redis:
    database: 1
    host: lunatic.ren
    password: LunaticLunatic
    port: 6379
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    username: //
    password: //
logging:
  level:
    com:
      scientific: debug